---
- name: Install and activate Qualys Agent on Ubuntu and AlmaLinux
  hosts: all
  become: true
  vars:
    qualys_agent_rpm_src: "/home/semaphore/QualysCloudAgent-6.rpm"
    qualys_agent_deb_src: "/home/semaphore/QualysCloudAgent_1.deb"
    
    qualys_activation_key: "f749af44-8c55-4f52-8a7b-a8583aec5bde"
    qualys_customer_id: "564896bd-efd2-6cde-8182-82e5936636d1"
    qualys_server_uri: "https://qagpublic.qg2.apps.qualys.com/CloudAgent/"
    qualys_agent_service_name: "qualys-cloud-agent"

  tasks:
    - name: Determine OS family
      ansible.builtin.set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Set installer source and destination paths based on OS family
      set_fact:
        qualys_agent_src_path: "{{ qualys_agent_deb_src if os_family == 'Debian' else qualys_agent_rpm_src }}"
        qualys_agent_dest_path: "/tmp/qualys-agent.{{ 'deb' if os_family == 'Debian' else 'rpm' }}"

    - name: Copy the appropriate Qualys agent installation file to the destination server
      ansible.builtin.copy:
        src: "{{ qualys_agent_src_path }}"
        dest: "{{ qualys_agent_dest_path }}"
        mode: '0755'

    - name: Install Qualys agent on Ubuntu
      ansible.builtin.apt:
        deb: "{{ qualys_agent_dest_path }}"
      when: os_family == "Debian"

    - name: Install Qualys agent on AlmaLinux
      ansible.builtin.yum:
        name: "{{ qualys_agent_dest_path }}"
        state: present
      when: os_family == "RedHat"

    - name: Activate Qualys agent
      ansible.builtin.command: >
        /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh
        ActivationId={{ qualys_activation_key }}
        CustomerId={{ qualys_customer_id }}
        ServerUri={{ qualys_server_uri }}
      args:
        creates: "/etc/qualys/cloud-agent.conf"

    - name: Enable and start Qualys Cloud Agent service
