---
- name: Check OS version and manage updates
  hosts: all
  become: yes
  tasks:
    - name: Gather OS information
      ansible.builtin.setup:
        gather_subset:
          - 'hardware'
          - 'network'
          - 'virtual'
          - 'facter'
          - 'ohai'
          - 'distribution'
      register: system_info

    - name: Print OS version
      ansible.builtin.debug:
        msg: "OS Version: {{ system_info.ansible_facts['ansible_distribution'] }} {{ system_info.ansible_facts['ansible_distribution_version'] }}"

    - name: Check if there are updates pending (for Debian/Ubuntu)
      ansible.builtin.shell: apt-get -s upgrade | grep "upgraded,"
      when: ansible_facts['os_family'] == "Debian"
      register: apt_updates_pending
      changed_when: apt_updates_pending.stdout != ""

    - name: Run updates (for Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
      when: apt_updates_pending.stdout != ""

    - name: Check for updates
      yum:
      list: updates
      register: yum_updates_pending

    - debug:
        var: yum_updates_pending

    - name: Run updates (for RedHat/CentOS)
      when: yum_updates_pending.results | length > 0
      ...
