---
- name: Install or upgrade Qualys Agent on Ubuntu and AlmaLinux
  hosts: all
  become: true
  vars:
    qualys_agent_rpm_src: "/home/semaphore/QualysCloudAgent-6.rpm"
    qualys_agent_deb_src: "/home/semaphore/QualysCloudAgent_1.deb"

    qualys_activation_key: "f749af44-8c55-4f52-8a7b-a8583aec5bde"
    qualys_customer_id: "564896bd-efd2-6cde-8182-82e5936636d1"
    qualys_server_uri: "https://qagpublic.qg2.apps.qualys.com/CloudAgent/"
    qualys_agent_service_name: "qualys-cloud-agent"

  tasks:
    - name: Determine OS family
      set_fact:
        os_family: "{{ ansible_os_family }}"

    - name: Check if Qualys agent is already installed
      shell: rpm -q qualys-cloud-agent || dpkg -s qualys-cloud-agent
      register: qualys_installed
      ignore_errors: true

    - name: Stop and remove old Qualys agent on RHEL/AlmaLinux
      block:
        - name: Stop Qualys agent service
          ansible.builtin.systemd:
            name: "{{ qualys_agent_service_name }}"
            state: stopped
          ignore_errors: yes

        - name: Remove Qualys agent RPM
          ansible.builtin.yum:
            name: qualys-cloud-agent
            state: absent
      when: os_family == "RedHat" and qualys_installed.rc == 0

    - name: Stop and remove old Qualys agent on Ubuntu/Debian
      block:
        - name: Stop Qualys agent service
          ansible.builtin.systemd:
            name: "{{ qualys_agent_service_name }}"
            state: stopped
          ignore_errors: yes

        - name: Remove Qualys agent DEB
          ansible.builtin.apt:
            name: qualys-cloud-agent
            state: absent
            purge: yes
      when: os_family == "Debian" and qualys_installed.rc == 0

    - name: Set installer source and destination paths
      set_fact:
        qualys_agent_src_path: "{{ qualys_agent_deb_src if os_family == 'Debian' else qualys_agent_rpm_src }}"
        qualys_agent_dest_path: "/tmp/qualys-agent.{{ 'deb' if os_family == 'Debian' else 'rpm' }}"

    - name: Copy Qualys agent installation file
      copy:
        src: "{{ qualys_agent_src_path }}"
        dest: "{{ qualys_agent_dest_path }}"
        mode: '0755'

    - name: Install Qualys agent on Ubuntu
      apt:
        deb: "{{ qualys_agent_dest_path }}"
      when: os_family == "Debian"

    - name: Install Qualys agent on AlmaLinux
      yum:
        name: "{{ qualys_agent_dest_path }}"
        state: present
      when: os_family == "RedHat"

    - name: Activate Qualys agent
      command: >
        /usr/local/qualys/cloud-agent/bin/qualys-cloud-agent.sh
        ActivationId={{ qualys_activation_key }}
        CustomerId={{ qualys_customer_id }}
        ServerUri={{ qualys_server_uri }}
      args:
        creates: "/etc/qualys/cloud-agent.conf"

    - name: Enable and start Qualys Cloud Agent service
      systemd:
        name: "{{ qualys_agent_service_name }}"
        enabled: true
        state: started

    - name: Wait for Qualys agent log
      wait_for:
        path: /var/log/qualys/qualys-cloud-agent.log
        timeout: 30

    - name: Check activation success in logs
      shell: grep -i "activation.*success" /var/log/qualys/qualys-cloud-agent.log || true
      register: qualys_activation_log
      changed_when: false

    - name: Show activation result
      debug:
        msg: >
          Qualys activation result: {{
            '✅ Activation successful!' if qualys_activation_log.stdout else '❌ Activation not confirmed in log. Check the log manually.'
          }}

    - name: Confirm Qualys Cloud Agent service is running
      systemd:
        name: "{{ qualys_agent_service_name }}"
        state: started
        enabled: true
      register: service_status

    - name: Show service status
      debug:
        msg: >
          Service Status: {{
            '✅ Running' if service_status.status.ActiveState == 'active' else '❌ Not running. Please check the service manually.'
          }}
