---
- name: Copy and install SnowAgent on AlmaLinux 8 machines
  hosts: 10.3.168.22
  become: yes
  tasks:
    - name: Copy SnowAgent installation file to destination
      copy:
        src: /home/nathaniela/snowagent-7.0.0-x64.rpm
        dest: /tmp/snowagent-7.0.0-x64.rpm
      register: copy_result

    - name: Install SnowAgent
      command: rpm -i /tmp/snowagent-7.0.0-x64.rpm
      ignore_errors: yes

    - name: Check if SnowAgent is installed
      command: find / -name snowagent
      register: snowagent_installed
      ignore_errors: yes

    - name: Get SnowAgent version
      command: rpm -q snowagent
      when: snowagent_installed.rc == 0
      register: snowagent_version

    - name: Output SnowAgent version
      debug:
        msg: "SnowAgent version: {{ snowagent_version.stdout }}"
      when: snowagent_installed.rc == 0

    - name: Output SnowAgent not installed
      debug:
        msg: "SnowAgent installation failed or SnowAgent is not installed."
      when: snowagent_installed.rc != 0
      
    - name: Copy Splunkforwarder installation file to destination
      copy:
        src: /home/nathaniela/splunkforwarder-9.2.0.1-d8ae995bf219.x86_64.rpm
        dest: /tmp/splunkforwarder-9.2.0.1-d8ae995bf219.x86_64.rpm
      register: copy_result

    - name: Install Splunkforwarder
      command: rpm -i /tmp/splunkforwarder-9.2.0.1-d8ae995bf219.x86_64.rpm

    - name: Check if Splunkforwarder is installed
      command: find / -name splunkforwarder
      register: splunkforwarder_installed
      ignore_errors: yes

    - name: Get Splunkforwarder version
      command: rpm -q splunkforwarder
      when: splunkforwarder_installed.rc == 0
      register: splunkforwarder_version

    - name: Output Splunkforwarder version
      debug:
        msg: "Splunkforwarder version: {{ splunkforwarder_version.stdout }}"
      when: splunkforwarder_installed.rc == 0

    - name: Output Splunkforwarder not installed
      debug:
        msg: "Splunkforwarder installation failed or SnowAgent is not installed."
      when: splunkforwarder_installed.rc != 0
