---
- name: Gather specific OS information and save to CSV
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Gather specific OS information
      ansible.builtin.setup:
        gather_subset:
          - 'min'
          - 'kernel'
          - 'kernel_version'
          - 'distribution'
          - 'distribution_version'
          - 'hardware'
        gather_timeout: 30
      register: system_info

    - name: Create CSV header
      local_action:
        module: copy
        dest: /tmp/os_info.csv
        content: "hostname,os_family,kernel,kernel_version,distribution,distribution_version,architecture\n"
      run_once: true

    - name: Append OS information to CSV
      local_action:
        module: lineinfile
        path: /tmp/os_info.csv
        line: "{{ inventory_hostname }},{{ system_info.ansible_facts['ansible_os_family'] }},{{ system_info.ansible_facts['ansible_kernel'] }},{{ system_info.ansible_facts['ansible_kernel_version'] }},{{ system_info.ansible_facts['ansible_distribution'] }},{{ system_info.ansible_facts['ansible_distribution_version'] }},{{ system_info.ansible_facts['ansible_architecture'] }}"
        create: yes
