---
- name: Gather specific OS information and save to CSV on Ansible server
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Gather specific OS information
      ansible.builtin.setup:
        gather_subset:
          - 'min'
          - 'kernel'
          - 'hardware'
        gather_timeout: 30
      register: system_info

    - name: Get current date in DD/MM/YYYY format
      ansible.builtin.command: date +"%d/%m/%Y"
      register: current_date

    - name: Get system uptime in minutes
      ansible.builtin.command: awk '{print int($1)}' /proc/uptime
      register: system_uptime

    - name: Ensure the CSV file exists with a header on Ansible server
      ansible.builtin.lineinfile:
        path: /home/nathaniela/os_info.csv
        line: "hostname,os_family,kernel,kernel_version,distribution,distribution_version,architecture,date,uptime_minutes"
        create: yes
        state: present
      delegate_to: localhost
      run_once: true

    - name: Append OS information to CSV on Ansible server
      ansible.builtin.lineinfile:
        path: /home/nathaniela/os_info.csv
        line: "{{ inventory_hostname }},{{ system_info.ansible_facts['ansible_os_family'] }},{{ system_info.ansible_facts['ansible_kernel'] }},{{ system_info.ansible_facts['ansible_kernel_version'] }},{{ system_info.ansible_facts['ansible_distribution'] }},{{ system_info.ansible_facts['ansible_distribution_version'] }},{{ system_info.ansible_facts['ansible_architecture'] }},{{ current_date.stdout }},{{ (system_uptime.stdout | int / 60) | round(0) }}"
        create: yes
      delegate_to: localhost
