---
- name: Install Elastic Agent on Linux
  hosts: Prod
  become: yes
  tasks:
    - name: Copy Elastic Agent tarball to destination
      ansible.builtin.copy:
        src: "/home/nathaniela/elastic-agent-8.12.2-linux-x86_64.tar.gz"  # Replace with your local path
        dest: "/tmp/elastic-agent-8.12.2-linux-x86_64.tar.gz"

    - name: Extract Elastic Agent tarball
      ansible.builtin.unarchive:
        src: "/tmp/elastic-agent-8.12.2-linux-x86_64.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Install Elastic Agent
      ansible.builtin.command:
      chdir: "/tmp/elastic-agent-8.12.2-linux-x86_64"
        cmd: "./elastic-agent install --url=https://elastic-fleet.lexisnexis.com:8220 --enrollment-token=TnVjeUNZOEJOWW1vVUUxbjJuUlA6cE1OSXFRd0hRSVNKNWtpM2J5RW83dw=="
        become: yes

    - name: Clean up Elastic A gent tarball
      ansible.builtin.file:
        path: "/tmp/elastic-agent-8.12.2-linux-x86_64.tar.gz"
        state: absent

    - name: Clean up extracted Elastic Agent directory
      ansible.builtin.file:
        path: "/tmp/elastic-agent-8.12.2-linux-x86_64"
        state: absent
        recurse: yes
