---
- name: Copy and execute a script on all remote hosts
  hosts: all
  become: yes
  vars:
    script_src: "/home/nathaniela/add_user_servicenow.sh"
    script_dest: "/tmp/add_user_servicenow.sh"

  tasks:
    - name: Copy script from Ansible control node to remote host
      copy:
        src: "{{ script_src }}"
        dest: "{{ script_dest }}"
        mode: '0755'
      delegate_to: localhost
      run_once: true  # copy only once if using multiple hosts

    - name: Copy from delegate machine to target host
      fetch:
        src: "{{ script_dest }}"
        dest: "/tmp/add_user_servicenow.sh"
        flat: yes

    - name: Set execute permission (in case fetch didn't preserve)
      file:
        path: "/tmp/add_user_servicenow.sh"
        mode: '0755'

    - name: Run the script
      command: "/bin/bash /tmp/add_user_servicenow.sh"
