---
- name: Copy and run the add_user_servicenow script on all hosts
  hosts: all
  become: yes
  vars:
    script_src: "/home/nathaniela/add_user_servicenow.sh"
    script_dest: "/tmp/add_user_servicenow.sh"

  tasks:
    - name: Ensure the source script exists on control node
      stat:
        path: "{{ script_src }}"
      register: script_stat
      delegate_to: localhost

    - name: Fail if script doesn't exist
      fail:
        msg: "Script {{ script_src }} does not exist on the control node!"
      when: not script_stat.stat.exists
      delegate_to: localhost

    - name: Copy the script to remote host
      copy:
        src: "{{ script_src }}"
        dest: "{{ script_dest }}"
        mode: '0755'

    - name: Run the script on remote host
      command: bash "{{ script_dest }}"
