---
- name: Copy and run the add_user script on all hosts
  hosts: all
  become: yes
  vars:
    script_src: "/home/nathaniela/add_user_servicenow.sh"
    script_dest: "/tmp/add_user_servicenow.sh"

  tasks:
    - name: Copy the script to remote host
      copy:
        src: "{{ script_src }}"
        dest: "{{ script_dest }}"
        mode: '0755'

    - name: Run the script on remote host
      command: bash "{{ script_dest }}"
